name: InnerEye
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - pip=20.1.1
  - python=3.7.3
  - pytorch=1.10.0
  - python-blosc=1.7.0
  - torchvision=0.11.1
  - pip:
      - -r requirements.txt
